server:
  port: 8080
  servlet:
    context-path: /vticket

spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/vticket_test
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DB_PASSWORD:root}
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/vticket_test
      database: vticket_test
      host: localhost
      port: 27017

    # Redis
    redis:
      host: localhost
      port: 6379

    # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # Email
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#  messages:
#    basename: properties/messages
#    encoding: UTF-8
#    fallback-to-system-locale: false

app:
  mail:
    from: ${MAIL_FROM}

# JWT
jwt:
  signerKey: ${JWT_SIGNER_KEY:your-256-bit-secret}

# Logging
logging:
  config: classpath:log4j2.xml
  level:
    com.vticket.vticket: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG
    org.springframework.web: DEBUG
    root: INFO

  # Static resources
  spring:
    web:
      resources:
      static-locations:
        classpath:/static/,file:uploads/

momo:
  partnerCode: MOMO
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  redirectUrl: https://localhost:8080/vticket/momo/return
  ipnUrl: https://localhost:8080/vticket/momo/ipn-handler
  accessKey: F8BBA842ECF85
  secretKey: K951B6PE1waDMi640xX08PD3vg6EkVlz
  requestType: captureWallet

