server:
  port: 8080
  servlet:
    context-path: /vticket

spring:
  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/vticket_test
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: 12345
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/vticket_test
      database: vticket_test
      host: localhost
      port: 27017

# Redis
    redis:
      host: localhost
      port: 6379
  mail:
    host: ${MAIL_HOST:smtp.example.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your_username}
    password: ${MAIL_PASSWORD:your_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  signerKey: cdOjoneRSm7ajl1RsOznZmSEYkd+6NnRN5S7fj2QtH/Rhheb6QnC8m1SGzznV75D

# Logging Configuration
logging:
  config: classpath:log4j2.xml
  level:
    com.vticket.vticket: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    io.jsonwebtoken: DEBUG
    org.springframework.web: DEBUG
    root: INFO

app:
  mail:
    from: ${MAIL_FROM:no-reply@vticket.local}

